version: '3.8'

# Local development overrides
services:
  gateway:
    environment:
      - GATEWAY_LOGGING_LEVEL=debug

  user-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"

  catalog-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5100"
