// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: streaming/v1/streaming.proto

package streamingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingService_GetStreamingInfo_FullMethodName    = "/streaming.v1.StreamingService/GetStreamingInfo"
	StreamingService_GetProgress_FullMethodName         = "/streaming.v1.StreamingService/GetProgress"
	StreamingService_GetContinueWatching_FullMethodName = "/streaming.v1.StreamingService/GetContinueWatching"
)

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamingService provides streaming metadata, watch progress,
// and continue-watching functionality.
type StreamingServiceClient interface {
	// GetStreamingInfo returns streaming metadata for a content item.
	GetStreamingInfo(ctx context.Context, in *GetStreamingInfoRequest, opts ...grpc.CallOption) (*StreamingInfoResponse, error)
	// GetProgress returns a user's watch position for specific content.
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	// GetContinueWatching returns the user's list of in-progress content,
	// sorted by most recently watched.
	GetContinueWatching(ctx context.Context, in *GetContinueWatchingRequest, opts ...grpc.CallOption) (*ContinueWatchingResponse, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) GetStreamingInfo(ctx context.Context, in *GetStreamingInfoRequest, opts ...grpc.CallOption) (*StreamingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamingInfoResponse)
	err := c.cc.Invoke(ctx, StreamingService_GetStreamingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, StreamingService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) GetContinueWatching(ctx context.Context, in *GetContinueWatchingRequest, opts ...grpc.CallOption) (*ContinueWatchingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueWatchingResponse)
	err := c.cc.Invoke(ctx, StreamingService_GetContinueWatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility.
//
// StreamingService provides streaming metadata, watch progress,
// and continue-watching functionality.
type StreamingServiceServer interface {
	// GetStreamingInfo returns streaming metadata for a content item.
	GetStreamingInfo(context.Context, *GetStreamingInfoRequest) (*StreamingInfoResponse, error)
	// GetProgress returns a user's watch position for specific content.
	GetProgress(context.Context, *GetProgressRequest) (*ProgressResponse, error)
	// GetContinueWatching returns the user's list of in-progress content,
	// sorted by most recently watched.
	GetContinueWatching(context.Context, *GetContinueWatchingRequest) (*ContinueWatchingResponse, error)
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServiceServer struct{}

func (UnimplementedStreamingServiceServer) GetStreamingInfo(context.Context, *GetStreamingInfoRequest) (*StreamingInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamingInfo not implemented")
}
func (UnimplementedStreamingServiceServer) GetProgress(context.Context, *GetProgressRequest) (*ProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedStreamingServiceServer) GetContinueWatching(context.Context, *GetContinueWatchingRequest) (*ContinueWatchingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContinueWatching not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}
func (UnimplementedStreamingServiceServer) testEmbeddedByValue()                          {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_GetStreamingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).GetStreamingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_GetStreamingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).GetStreamingInfo(ctx, req.(*GetStreamingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_GetContinueWatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContinueWatchingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).GetContinueWatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_GetContinueWatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).GetContinueWatching(ctx, req.(*GetContinueWatchingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStreamingInfo",
			Handler:    _StreamingService_GetStreamingInfo_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _StreamingService_GetProgress_Handler,
		},
		{
			MethodName: "GetContinueWatching",
			Handler:    _StreamingService_GetContinueWatching_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streaming/v1/streaming.proto",
}
