// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: subscription/v1/subscription.proto

package subscriptionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionQueryService_GetUserSubscription_FullMethodName = "/subscription.v1.SubscriptionQueryService/GetUserSubscription"
	SubscriptionQueryService_GetUserTier_FullMethodName         = "/subscription.v1.SubscriptionQueryService/GetUserTier"
)

// SubscriptionQueryServiceClient is the client API for SubscriptionQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubscriptionQueryService provides read-only queries for user subscriptions.
// Write operations (create, cancel, change plan) use HTTP REST with Saga pattern.
type SubscriptionQueryServiceClient interface {
	// GetUserSubscription returns the active subscription details for a user.
	GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*GetUserSubscriptionResponse, error)
	// GetUserTier returns the user's current subscription tier.
	GetUserTier(ctx context.Context, in *GetUserTierRequest, opts ...grpc.CallOption) (*GetUserTierResponse, error)
}

type subscriptionQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionQueryServiceClient(cc grpc.ClientConnInterface) SubscriptionQueryServiceClient {
	return &subscriptionQueryServiceClient{cc}
}

func (c *subscriptionQueryServiceClient) GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*GetUserSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionQueryService_GetUserSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionQueryServiceClient) GetUserTier(ctx context.Context, in *GetUserTierRequest, opts ...grpc.CallOption) (*GetUserTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTierResponse)
	err := c.cc.Invoke(ctx, SubscriptionQueryService_GetUserTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionQueryServiceServer is the server API for SubscriptionQueryService service.
// All implementations must embed UnimplementedSubscriptionQueryServiceServer
// for forward compatibility.
//
// SubscriptionQueryService provides read-only queries for user subscriptions.
// Write operations (create, cancel, change plan) use HTTP REST with Saga pattern.
type SubscriptionQueryServiceServer interface {
	// GetUserSubscription returns the active subscription details for a user.
	GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*GetUserSubscriptionResponse, error)
	// GetUserTier returns the user's current subscription tier.
	GetUserTier(context.Context, *GetUserTierRequest) (*GetUserTierResponse, error)
	mustEmbedUnimplementedSubscriptionQueryServiceServer()
}

// UnimplementedSubscriptionQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionQueryServiceServer struct{}

func (UnimplementedSubscriptionQueryServiceServer) GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*GetUserSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSubscription not implemented")
}
func (UnimplementedSubscriptionQueryServiceServer) GetUserTier(context.Context, *GetUserTierRequest) (*GetUserTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTier not implemented")
}
func (UnimplementedSubscriptionQueryServiceServer) mustEmbedUnimplementedSubscriptionQueryServiceServer() {
}
func (UnimplementedSubscriptionQueryServiceServer) testEmbeddedByValue() {}

// UnsafeSubscriptionQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionQueryServiceServer will
// result in compilation errors.
type UnsafeSubscriptionQueryServiceServer interface {
	mustEmbedUnimplementedSubscriptionQueryServiceServer()
}

func RegisterSubscriptionQueryServiceServer(s grpc.ServiceRegistrar, srv SubscriptionQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionQueryService_ServiceDesc, srv)
}

func _SubscriptionQueryService_GetUserSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionQueryServiceServer).GetUserSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionQueryService_GetUserSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionQueryServiceServer).GetUserSubscription(ctx, req.(*GetUserSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionQueryService_GetUserTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionQueryServiceServer).GetUserTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionQueryService_GetUserTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionQueryServiceServer).GetUserTier(ctx, req.(*GetUserTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionQueryService_ServiceDesc is the grpc.ServiceDesc for SubscriptionQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.v1.SubscriptionQueryService",
	HandlerType: (*SubscriptionQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSubscription",
			Handler:    _SubscriptionQueryService_GetUserSubscription_Handler,
		},
		{
			MethodName: "GetUserTier",
			Handler:    _SubscriptionQueryService_GetUserTier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription/v1/subscription.proto",
}
