// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: subscription/v1/subscription.proto

package subscriptionv1

import (
	v1 "github.com/streamvault/gateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscriptionStatus tracks the lifecycle of a subscription.
type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED     SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_PENDING_PAYMENT SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE          SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED       SubscriptionStatus = 3
	SubscriptionStatus_SUBSCRIPTION_STATUS_EXPIRED         SubscriptionStatus = 4
	SubscriptionStatus_SUBSCRIPTION_STATUS_FAILED          SubscriptionStatus = 5
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_PENDING_PAYMENT",
		2: "SUBSCRIPTION_STATUS_ACTIVE",
		3: "SUBSCRIPTION_STATUS_CANCELLED",
		4: "SUBSCRIPTION_STATUS_EXPIRED",
		5: "SUBSCRIPTION_STATUS_FAILED",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED":     0,
		"SUBSCRIPTION_STATUS_PENDING_PAYMENT": 1,
		"SUBSCRIPTION_STATUS_ACTIVE":          2,
		"SUBSCRIPTION_STATUS_CANCELLED":       3,
		"SUBSCRIPTION_STATUS_EXPIRED":         4,
		"SUBSCRIPTION_STATUS_FAILED":          5,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_v1_subscription_proto_enumTypes[0].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_subscription_v1_subscription_proto_enumTypes[0]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Plan           *PlanInfo              `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	Status         SubscriptionStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=subscription.v1.SubscriptionStatus" json:"status,omitempty"`
	PeriodStart    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	AutoRenew      bool                   `protobuf:"varint,7,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CancelledAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"` // Only set if status is CANCELLED
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserSubscriptionResponse) Reset() {
	*x = GetUserSubscriptionResponse{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionResponse) ProtoMessage() {}

func (x *GetUserSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserSubscriptionResponse) GetPlan() *PlanInfo {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *GetUserSubscriptionResponse) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *GetUserSubscriptionResponse) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *GetUserSubscriptionResponse) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *GetUserSubscriptionResponse) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *GetUserSubscriptionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserSubscriptionResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

type PlanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // "Basic", "Standard", "Premium"
	Tier          v1.SubscriptionTier    `protobuf:"varint,3,opt,name=tier,proto3,enum=common.v1.SubscriptionTier" json:"tier,omitempty"`
	PriceMonthly  float64                `protobuf:"fixed64,4,opt,name=price_monthly,json=priceMonthly,proto3" json:"price_monthly,omitempty"`
	MaxScreens    int32                  `protobuf:"varint,5,opt,name=max_screens,json=maxScreens,proto3" json:"max_screens,omitempty"`
	MaxQuality    string                 `protobuf:"bytes,6,opt,name=max_quality,json=maxQuality,proto3" json:"max_quality,omitempty"` // "720p", "1080p", "4K"
	Features      []string               `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanInfo) Reset() {
	*x = PlanInfo{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanInfo) ProtoMessage() {}

func (x *PlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanInfo.ProtoReflect.Descriptor instead.
func (*PlanInfo) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *PlanInfo) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanInfo) GetTier() v1.SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return v1.SubscriptionTier(0)
}

func (x *PlanInfo) GetPriceMonthly() float64 {
	if x != nil {
		return x.PriceMonthly
	}
	return 0
}

func (x *PlanInfo) GetMaxScreens() int32 {
	if x != nil {
		return x.MaxScreens
	}
	return 0
}

func (x *PlanInfo) GetMaxQuality() string {
	if x != nil {
		return x.MaxQuality
	}
	return ""
}

func (x *PlanInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type GetUserTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTierRequest) Reset() {
	*x = GetUserTierRequest{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTierRequest) ProtoMessage() {}

func (x *GetUserTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTierRequest.ProtoReflect.Descriptor instead.
func (*GetUserTierRequest) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserTierRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.SubscriptionTier    `protobuf:"varint,1,opt,name=tier,proto3,enum=common.v1.SubscriptionTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTierResponse) Reset() {
	*x = GetUserTierResponse{}
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTierResponse) ProtoMessage() {}

func (x *GetUserTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTierResponse.ProtoReflect.Descriptor instead.
func (*GetUserTierResponse) Descriptor() ([]byte, []int) {
	return file_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTierResponse) GetTier() v1.SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return v1.SubscriptionTier(0)
}

var File_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"\"subscription/v1/subscription.proto\x12\x0fsubscription.v1\x1a\x16common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x1aGetUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xde\x03\n" +
	"\x1bGetUserSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x04plan\x18\x03 \x01(\v2\x19.subscription.v1.PlanInfoR\x04plan\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.subscription.v1.SubscriptionStatusR\x06status\x12=\n" +
	"\fperiod_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\a \x01(\bR\tautoRenew\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcancelled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"\xeb\x01\n" +
	"\bPlanInfo\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x1b.common.v1.SubscriptionTierR\x04tier\x12#\n" +
	"\rprice_monthly\x18\x04 \x01(\x01R\fpriceMonthly\x12\x1f\n" +
	"\vmax_screens\x18\x05 \x01(\x05R\n" +
	"maxScreens\x12\x1f\n" +
	"\vmax_quality\x18\x06 \x01(\tR\n" +
	"maxQuality\x12\x1a\n" +
	"\bfeatures\x18\a \x03(\tR\bfeatures\"-\n" +
	"\x12GetUserTierRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x13GetUserTierResponse\x12/\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.v1.SubscriptionTierR\x04tier*\xe6\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12'\n" +
	"#SUBSCRIPTION_STATUS_PENDING_PAYMENT\x10\x01\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x02\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x03\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_EXPIRED\x10\x04\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_FAILED\x10\x052\xe6\x01\n" +
	"\x18SubscriptionQueryService\x12p\n" +
	"\x13GetUserSubscription\x12+.subscription.v1.GetUserSubscriptionRequest\x1a,.subscription.v1.GetUserSubscriptionResponse\x12X\n" +
	"\vGetUserTier\x12#.subscription.v1.GetUserTierRequest\x1a$.subscription.v1.GetUserTierResponseBiZCgithub.com/streamvault/gateway/proto/subscription/v1;subscriptionv1\xaa\x02!StreamVault.Proto.Subscription.V1b\x06proto3"

var (
	file_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_subscription_v1_subscription_proto_rawDescData []byte
)

func file_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_subscription_v1_subscription_proto_rawDescData
}

var file_subscription_v1_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_subscription_v1_subscription_proto_goTypes = []any{
	(SubscriptionStatus)(0),             // 0: subscription.v1.SubscriptionStatus
	(*GetUserSubscriptionRequest)(nil),  // 1: subscription.v1.GetUserSubscriptionRequest
	(*GetUserSubscriptionResponse)(nil), // 2: subscription.v1.GetUserSubscriptionResponse
	(*PlanInfo)(nil),                    // 3: subscription.v1.PlanInfo
	(*GetUserTierRequest)(nil),          // 4: subscription.v1.GetUserTierRequest
	(*GetUserTierResponse)(nil),         // 5: subscription.v1.GetUserTierResponse
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
	(v1.SubscriptionTier)(0),            // 7: common.v1.SubscriptionTier
}
var file_subscription_v1_subscription_proto_depIdxs = []int32{
	3,  // 0: subscription.v1.GetUserSubscriptionResponse.plan:type_name -> subscription.v1.PlanInfo
	0,  // 1: subscription.v1.GetUserSubscriptionResponse.status:type_name -> subscription.v1.SubscriptionStatus
	6,  // 2: subscription.v1.GetUserSubscriptionResponse.period_start:type_name -> google.protobuf.Timestamp
	6,  // 3: subscription.v1.GetUserSubscriptionResponse.period_end:type_name -> google.protobuf.Timestamp
	6,  // 4: subscription.v1.GetUserSubscriptionResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 5: subscription.v1.GetUserSubscriptionResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	7,  // 6: subscription.v1.PlanInfo.tier:type_name -> common.v1.SubscriptionTier
	7,  // 7: subscription.v1.GetUserTierResponse.tier:type_name -> common.v1.SubscriptionTier
	1,  // 8: subscription.v1.SubscriptionQueryService.GetUserSubscription:input_type -> subscription.v1.GetUserSubscriptionRequest
	4,  // 9: subscription.v1.SubscriptionQueryService.GetUserTier:input_type -> subscription.v1.GetUserTierRequest
	2,  // 10: subscription.v1.SubscriptionQueryService.GetUserSubscription:output_type -> subscription.v1.GetUserSubscriptionResponse
	5,  // 11: subscription.v1.SubscriptionQueryService.GetUserTier:output_type -> subscription.v1.GetUserTierResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_subscription_v1_subscription_proto_init() }
func file_subscription_v1_subscription_proto_init() {
	if File_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_v1_subscription_proto_rawDesc), len(file_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_v1_subscription_proto_depIdxs,
		EnumInfos:         file_subscription_v1_subscription_proto_enumTypes,
		MessageInfos:      file_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_subscription_v1_subscription_proto = out.File
	file_subscription_v1_subscription_proto_goTypes = nil
	file_subscription_v1_subscription_proto_depIdxs = nil
}
