// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentType represents the type of content in the catalog.
type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_MOVIE       ContentType = 1
	ContentType_CONTENT_TYPE_SERIES      ContentType = 2
	ContentType_CONTENT_TYPE_EPISODE     ContentType = 3
	ContentType_CONTENT_TYPE_DOCUMENTARY ContentType = 4
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_MOVIE",
		2: "CONTENT_TYPE_SERIES",
		3: "CONTENT_TYPE_EPISODE",
		4: "CONTENT_TYPE_DOCUMENTARY",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_MOVIE":       1,
		"CONTENT_TYPE_SERIES":      2,
		"CONTENT_TYPE_EPISODE":     3,
		"CONTENT_TYPE_DOCUMENTARY": 4,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// SubscriptionTier defines the user's subscription level.
type SubscriptionTier int32

const (
	SubscriptionTier_SUBSCRIPTION_TIER_UNSPECIFIED SubscriptionTier = 0
	SubscriptionTier_SUBSCRIPTION_TIER_FREE        SubscriptionTier = 1
	SubscriptionTier_SUBSCRIPTION_TIER_BASIC       SubscriptionTier = 2
	SubscriptionTier_SUBSCRIPTION_TIER_STANDARD    SubscriptionTier = 3
	SubscriptionTier_SUBSCRIPTION_TIER_PREMIUM     SubscriptionTier = 4
)

// Enum value maps for SubscriptionTier.
var (
	SubscriptionTier_name = map[int32]string{
		0: "SUBSCRIPTION_TIER_UNSPECIFIED",
		1: "SUBSCRIPTION_TIER_FREE",
		2: "SUBSCRIPTION_TIER_BASIC",
		3: "SUBSCRIPTION_TIER_STANDARD",
		4: "SUBSCRIPTION_TIER_PREMIUM",
	}
	SubscriptionTier_value = map[string]int32{
		"SUBSCRIPTION_TIER_UNSPECIFIED": 0,
		"SUBSCRIPTION_TIER_FREE":        1,
		"SUBSCRIPTION_TIER_BASIC":       2,
		"SUBSCRIPTION_TIER_STANDARD":    3,
		"SUBSCRIPTION_TIER_PREMIUM":     4,
	}
)

func (x SubscriptionTier) Enum() *SubscriptionTier {
	p := new(SubscriptionTier)
	*p = x
	return p
}

func (x SubscriptionTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionTier) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (SubscriptionTier) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[1]
}

func (x SubscriptionTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionTier.Descriptor instead.
func (SubscriptionTier) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

// VideoStatus tracks the lifecycle of a video's encoding pipeline.
type VideoStatus int32

const (
	VideoStatus_VIDEO_STATUS_UNSPECIFIED  VideoStatus = 0
	VideoStatus_VIDEO_STATUS_NOT_UPLOADED VideoStatus = 1
	VideoStatus_VIDEO_STATUS_UPLOADING    VideoStatus = 2
	VideoStatus_VIDEO_STATUS_QUEUED       VideoStatus = 3
	VideoStatus_VIDEO_STATUS_ENCODING     VideoStatus = 4
	VideoStatus_VIDEO_STATUS_READY        VideoStatus = 5
	VideoStatus_VIDEO_STATUS_ERROR        VideoStatus = 6
)

// Enum value maps for VideoStatus.
var (
	VideoStatus_name = map[int32]string{
		0: "VIDEO_STATUS_UNSPECIFIED",
		1: "VIDEO_STATUS_NOT_UPLOADED",
		2: "VIDEO_STATUS_UPLOADING",
		3: "VIDEO_STATUS_QUEUED",
		4: "VIDEO_STATUS_ENCODING",
		5: "VIDEO_STATUS_READY",
		6: "VIDEO_STATUS_ERROR",
	}
	VideoStatus_value = map[string]int32{
		"VIDEO_STATUS_UNSPECIFIED":  0,
		"VIDEO_STATUS_NOT_UPLOADED": 1,
		"VIDEO_STATUS_UPLOADING":    2,
		"VIDEO_STATUS_QUEUED":       3,
		"VIDEO_STATUS_ENCODING":     4,
		"VIDEO_STATUS_READY":        5,
		"VIDEO_STATUS_ERROR":        6,
	}
)

func (x VideoStatus) Enum() *VideoStatus {
	p := new(VideoStatus)
	*p = x
	return p
}

func (x VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (VideoStatus) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[2]
}

func (x VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoStatus.Descriptor instead.
func (VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

// Pagination request parameters.
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PaginatedResponse carries pagination metadata in responses.
type PaginatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedResponse) Reset() {
	*x = PaginatedResponse{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedResponse) ProtoMessage() {}

func (x *PaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedResponse.ProtoReflect.Descriptor instead.
func (*PaginatedResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginatedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatedResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginatedResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginatedResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\tcommon.v1\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x86\x01\n" +
	"\x11PaginatedResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages*\x94\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTENT_TYPE_MOVIE\x10\x01\x12\x17\n" +
	"\x13CONTENT_TYPE_SERIES\x10\x02\x12\x18\n" +
	"\x14CONTENT_TYPE_EPISODE\x10\x03\x12\x1c\n" +
	"\x18CONTENT_TYPE_DOCUMENTARY\x10\x04*\xad\x01\n" +
	"\x10SubscriptionTier\x12!\n" +
	"\x1dSUBSCRIPTION_TIER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SUBSCRIPTION_TIER_FREE\x10\x01\x12\x1b\n" +
	"\x17SUBSCRIPTION_TIER_BASIC\x10\x02\x12\x1e\n" +
	"\x1aSUBSCRIPTION_TIER_STANDARD\x10\x03\x12\x1d\n" +
	"\x19SUBSCRIPTION_TIER_PREMIUM\x10\x04*\xca\x01\n" +
	"\vVideoStatus\x12\x1c\n" +
	"\x18VIDEO_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19VIDEO_STATUS_NOT_UPLOADED\x10\x01\x12\x1a\n" +
	"\x16VIDEO_STATUS_UPLOADING\x10\x02\x12\x17\n" +
	"\x13VIDEO_STATUS_QUEUED\x10\x03\x12\x19\n" +
	"\x15VIDEO_STATUS_ENCODING\x10\x04\x12\x16\n" +
	"\x12VIDEO_STATUS_READY\x10\x05\x12\x16\n" +
	"\x12VIDEO_STATUS_ERROR\x10\x06BWZ7github.com/streamvault/gateway/proto/common/v1;commonv1\xaa\x02\x1bStreamVault.Proto.Common.V1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_common_proto_goTypes = []any{
	(ContentType)(0),          // 0: common.v1.ContentType
	(SubscriptionTier)(0),     // 1: common.v1.SubscriptionTier
	(VideoStatus)(0),          // 2: common.v1.VideoStatus
	(*Pagination)(nil),        // 3: common.v1.Pagination
	(*PaginatedResponse)(nil), // 4: common.v1.PaginatedResponse
}
var file_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
