// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: streaming/v1/streaming.proto

package streamingv1

import (
	v1 "github.com/streamvault/gateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStreamingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamingInfoRequest) Reset() {
	*x = GetStreamingInfoRequest{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamingInfoRequest) ProtoMessage() {}

func (x *GetStreamingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStreamingInfoRequest) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamingInfoRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type StreamingInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ContentId          string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Status             v1.VideoStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.VideoStatus" json:"status,omitempty"`
	DurationSeconds    int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AvailableQualities []*QualityInfo         `protobuf:"bytes,4,rep,name=available_qualities,json=availableQualities,proto3" json:"available_qualities,omitempty"`
	ManifestPath       string                 `protobuf:"bytes,5,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	ThumbnailPath      string                 `protobuf:"bytes,6,opt,name=thumbnail_path,json=thumbnailPath,proto3" json:"thumbnail_path,omitempty"`
	PosterPath         string                 `protobuf:"bytes,7,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	EncodedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=encoded_at,json=encodedAt,proto3" json:"encoded_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamingInfoResponse) Reset() {
	*x = StreamingInfoResponse{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingInfoResponse) ProtoMessage() {}

func (x *StreamingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingInfoResponse.ProtoReflect.Descriptor instead.
func (*StreamingInfoResponse) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingInfoResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *StreamingInfoResponse) GetStatus() v1.VideoStatus {
	if x != nil {
		return x.Status
	}
	return v1.VideoStatus(0)
}

func (x *StreamingInfoResponse) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StreamingInfoResponse) GetAvailableQualities() []*QualityInfo {
	if x != nil {
		return x.AvailableQualities
	}
	return nil
}

func (x *StreamingInfoResponse) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

func (x *StreamingInfoResponse) GetThumbnailPath() string {
	if x != nil {
		return x.ThumbnailPath
	}
	return ""
}

func (x *StreamingInfoResponse) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *StreamingInfoResponse) GetEncodedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EncodedAt
	}
	return nil
}

// QualityInfo describes a single quality level available for streaming.
type QualityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // "360p", "720p", "1080p", "4K"
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,4,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	SegmentCount  int32                  `protobuf:"varint,5,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	MinTier       v1.SubscriptionTier    `protobuf:"varint,6,opt,name=min_tier,json=minTier,proto3,enum=common.v1.SubscriptionTier" json:"min_tier,omitempty"` // Minimum tier required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityInfo) Reset() {
	*x = QualityInfo{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityInfo) ProtoMessage() {}

func (x *QualityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityInfo.ProtoReflect.Descriptor instead.
func (*QualityInfo) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *QualityInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QualityInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *QualityInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *QualityInfo) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *QualityInfo) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *QualityInfo) GetMinTier() v1.SubscriptionTier {
	if x != nil {
		return x.MinTier
	}
	return v1.SubscriptionTier(0)
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProgressRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type ProgressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId       string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	PositionSeconds int64                  `protobuf:"varint,3,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Percentage      float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ProgressResponse) GetPositionSeconds() int64 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *ProgressResponse) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ProgressResponse) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProgressResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetContinueWatchingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max items to return; 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContinueWatchingRequest) Reset() {
	*x = GetContinueWatchingRequest{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContinueWatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContinueWatchingRequest) ProtoMessage() {}

func (x *GetContinueWatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContinueWatchingRequest.ProtoReflect.Descriptor instead.
func (*GetContinueWatchingRequest) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *GetContinueWatchingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetContinueWatchingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ContinueWatchingResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ContinueWatchingItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueWatchingResponse) Reset() {
	*x = ContinueWatchingResponse{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueWatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueWatchingResponse) ProtoMessage() {}

func (x *ContinueWatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueWatchingResponse.ProtoReflect.Descriptor instead.
func (*ContinueWatchingResponse) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *ContinueWatchingResponse) GetItems() []*ContinueWatchingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ContinueWatchingItem represents a content item the user has partially watched.
type ContinueWatchingItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl    string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	PositionSeconds int64                  `protobuf:"varint,4,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Percentage      float64                `protobuf:"fixed64,6,opt,name=percentage,proto3" json:"percentage,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContinueWatchingItem) Reset() {
	*x = ContinueWatchingItem{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueWatchingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueWatchingItem) ProtoMessage() {}

func (x *ContinueWatchingItem) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueWatchingItem.ProtoReflect.Descriptor instead.
func (*ContinueWatchingItem) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *ContinueWatchingItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ContinueWatchingItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContinueWatchingItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *ContinueWatchingItem) GetPositionSeconds() int64 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *ContinueWatchingItem) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ContinueWatchingItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ContinueWatchingItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_streaming_v1_streaming_proto protoreflect.FileDescriptor

const file_streaming_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1cstreaming/v1/streaming.proto\x12\fstreaming.v1\x1a\x16common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x17GetStreamingInfoRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\x85\x03\n" +
	"\x15StreamingInfoResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.common.v1.VideoStatusR\x06status\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x12J\n" +
	"\x13available_qualities\x18\x04 \x03(\v2\x19.streaming.v1.QualityInfoR\x12availableQualities\x12#\n" +
	"\rmanifest_path\x18\x05 \x01(\tR\fmanifestPath\x12%\n" +
	"\x0ethumbnail_path\x18\x06 \x01(\tR\rthumbnailPath\x12\x1f\n" +
	"\vposter_path\x18\a \x01(\tR\n" +
	"posterPath\x129\n" +
	"\n" +
	"encoded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tencodedAt\"\xd1\x01\n" +
	"\vQualityInfo\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12!\n" +
	"\fbitrate_kbps\x18\x04 \x01(\x05R\vbitrateKbps\x12#\n" +
	"\rsegment_count\x18\x05 \x01(\x05R\fsegmentCount\x126\n" +
	"\bmin_tier\x18\x06 \x01(\x0e2\x1b.common.v1.SubscriptionTierR\aminTier\"L\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\"\xfb\x01\n" +
	"\x10ProgressResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12)\n" +
	"\x10position_seconds\x18\x03 \x01(\x03R\x0fpositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"K\n" +
	"\x1aGetContinueWatchingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"T\n" +
	"\x18ContinueWatchingResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".streaming.v1.ContinueWatchingItemR\x05items\"\xa1\x02\n" +
	"\x14ContinueWatchingItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x12)\n" +
	"\x10position_seconds\x18\x04 \x01(\x03R\x0fpositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x03R\x0fdurationSeconds\x12\x1e\n" +
	"\n" +
	"percentage\x18\x06 \x01(\x01R\n" +
	"percentage\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xac\x02\n" +
	"\x10StreamingService\x12^\n" +
	"\x10GetStreamingInfo\x12%.streaming.v1.GetStreamingInfoRequest\x1a#.streaming.v1.StreamingInfoResponse\x12O\n" +
	"\vGetProgress\x12 .streaming.v1.GetProgressRequest\x1a\x1e.streaming.v1.ProgressResponse\x12g\n" +
	"\x13GetContinueWatching\x12(.streaming.v1.GetContinueWatchingRequest\x1a&.streaming.v1.ContinueWatchingResponseB`Z=github.com/streamvault/gateway/proto/streaming/v1;streamingv1\xaa\x02\x1eStreamVault.Proto.Streaming.V1b\x06proto3"

var (
	file_streaming_v1_streaming_proto_rawDescOnce sync.Once
	file_streaming_v1_streaming_proto_rawDescData []byte
)

func file_streaming_v1_streaming_proto_rawDescGZIP() []byte {
	file_streaming_v1_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_v1_streaming_proto_rawDesc), len(file_streaming_v1_streaming_proto_rawDesc)))
	})
	return file_streaming_v1_streaming_proto_rawDescData
}

var file_streaming_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_streaming_v1_streaming_proto_goTypes = []any{
	(*GetStreamingInfoRequest)(nil),    // 0: streaming.v1.GetStreamingInfoRequest
	(*StreamingInfoResponse)(nil),      // 1: streaming.v1.StreamingInfoResponse
	(*QualityInfo)(nil),                // 2: streaming.v1.QualityInfo
	(*GetProgressRequest)(nil),         // 3: streaming.v1.GetProgressRequest
	(*ProgressResponse)(nil),           // 4: streaming.v1.ProgressResponse
	(*GetContinueWatchingRequest)(nil), // 5: streaming.v1.GetContinueWatchingRequest
	(*ContinueWatchingResponse)(nil),   // 6: streaming.v1.ContinueWatchingResponse
	(*ContinueWatchingItem)(nil),       // 7: streaming.v1.ContinueWatchingItem
	(v1.VideoStatus)(0),                // 8: common.v1.VideoStatus
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
	(v1.SubscriptionTier)(0),           // 10: common.v1.SubscriptionTier
}
var file_streaming_v1_streaming_proto_depIdxs = []int32{
	8,  // 0: streaming.v1.StreamingInfoResponse.status:type_name -> common.v1.VideoStatus
	2,  // 1: streaming.v1.StreamingInfoResponse.available_qualities:type_name -> streaming.v1.QualityInfo
	9,  // 2: streaming.v1.StreamingInfoResponse.encoded_at:type_name -> google.protobuf.Timestamp
	10, // 3: streaming.v1.QualityInfo.min_tier:type_name -> common.v1.SubscriptionTier
	9,  // 4: streaming.v1.ProgressResponse.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 5: streaming.v1.ContinueWatchingResponse.items:type_name -> streaming.v1.ContinueWatchingItem
	9,  // 6: streaming.v1.ContinueWatchingItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: streaming.v1.StreamingService.GetStreamingInfo:input_type -> streaming.v1.GetStreamingInfoRequest
	3,  // 8: streaming.v1.StreamingService.GetProgress:input_type -> streaming.v1.GetProgressRequest
	5,  // 9: streaming.v1.StreamingService.GetContinueWatching:input_type -> streaming.v1.GetContinueWatchingRequest
	1,  // 10: streaming.v1.StreamingService.GetStreamingInfo:output_type -> streaming.v1.StreamingInfoResponse
	4,  // 11: streaming.v1.StreamingService.GetProgress:output_type -> streaming.v1.ProgressResponse
	6,  // 12: streaming.v1.StreamingService.GetContinueWatching:output_type -> streaming.v1.ContinueWatchingResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_streaming_v1_streaming_proto_init() }
func file_streaming_v1_streaming_proto_init() {
	if File_streaming_v1_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_v1_streaming_proto_rawDesc), len(file_streaming_v1_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_v1_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_v1_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_v1_streaming_proto_msgTypes,
	}.Build()
	File_streaming_v1_streaming_proto = out.File
	file_streaming_v1_streaming_proto_goTypes = nil
	file_streaming_v1_streaming_proto_depIdxs = nil
}
