// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: recommendation/v1/recommendation.proto

package recommendationv1

import (
	v1 "github.com/streamvault/gateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SectionType defines the kind of home page section.
type SectionType int32

const (
	SectionType_SECTION_TYPE_UNSPECIFIED         SectionType = 0
	SectionType_SECTION_TYPE_PERSONAL            SectionType = 1
	SectionType_SECTION_TYPE_TRENDING            SectionType = 2
	SectionType_SECTION_TYPE_BECAUSE_YOU_WATCHED SectionType = 3
	SectionType_SECTION_TYPE_GENRE               SectionType = 4
	SectionType_SECTION_TYPE_NEW                 SectionType = 5
)

// Enum value maps for SectionType.
var (
	SectionType_name = map[int32]string{
		0: "SECTION_TYPE_UNSPECIFIED",
		1: "SECTION_TYPE_PERSONAL",
		2: "SECTION_TYPE_TRENDING",
		3: "SECTION_TYPE_BECAUSE_YOU_WATCHED",
		4: "SECTION_TYPE_GENRE",
		5: "SECTION_TYPE_NEW",
	}
	SectionType_value = map[string]int32{
		"SECTION_TYPE_UNSPECIFIED":         0,
		"SECTION_TYPE_PERSONAL":            1,
		"SECTION_TYPE_TRENDING":            2,
		"SECTION_TYPE_BECAUSE_YOU_WATCHED": 3,
		"SECTION_TYPE_GENRE":               4,
		"SECTION_TYPE_NEW":                 5,
	}
)

func (x SectionType) Enum() *SectionType {
	p := new(SectionType)
	*p = x
	return p
}

func (x SectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_recommendation_v1_recommendation_proto_enumTypes[0].Descriptor()
}

func (SectionType) Type() protoreflect.EnumType {
	return &file_recommendation_v1_recommendation_proto_enumTypes[0]
}

func (x SectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SectionType.Descriptor instead.
func (SectionType) EnumDescriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max items; 0 = server default (20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendedItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecommendationsResponse) GetItems() []*RecommendedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RecommendedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ContentType   v1.ContentType         `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	AverageRating float64                `protobuf:"fixed64,6,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`       // Recommendation score (0.0 - 1.0)
	Algorithm     string                 `protobuf:"bytes,8,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // "hybrid", "collaborative", "content_based", "popularity"
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`       // Human-readable reason, e.g. "Because you watched Interstellar"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedItem) Reset() {
	*x = RecommendedItem{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedItem) ProtoMessage() {}

func (x *RecommendedItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedItem.ProtoReflect.Descriptor instead.
func (*RecommendedItem) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendedItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *RecommendedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendedItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *RecommendedItem) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

func (x *RecommendedItem) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *RecommendedItem) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *RecommendedItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendedItem) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RecommendedItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max items; 0 = server default (10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarRequest) Reset() {
	*x = GetSimilarRequest{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarRequest) ProtoMessage() {}

func (x *GetSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetSimilarRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSimilarRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSimilarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SimilarItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarResponse) Reset() {
	*x = GetSimilarResponse{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarResponse) ProtoMessage() {}

func (x *GetSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *GetSimilarResponse) GetItems() []*SimilarItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SimilarItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl    string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ContentType     v1.ContentType         `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"`
	ReleaseYear     int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	AverageRating   float64                `protobuf:"fixed64,6,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,7,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"` // Cosine similarity (0.0 - 1.0)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimilarItem) Reset() {
	*x = SimilarItem{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarItem) ProtoMessage() {}

func (x *SimilarItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarItem.ProtoReflect.Descriptor instead.
func (*SimilarItem) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *SimilarItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *SimilarItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimilarItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *SimilarItem) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

func (x *SimilarItem) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *SimilarItem) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *SimilarItem) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

type GetHomePageSectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomePageSectionsRequest) Reset() {
	*x = GetHomePageSectionsRequest{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomePageSectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomePageSectionsRequest) ProtoMessage() {}

func (x *GetHomePageSectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomePageSectionsRequest.ProtoReflect.Descriptor instead.
func (*GetHomePageSectionsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *GetHomePageSectionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHomePageSectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*HomePageSection     `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomePageSectionsResponse) Reset() {
	*x = GetHomePageSectionsResponse{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomePageSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomePageSectionsResponse) ProtoMessage() {}

func (x *GetHomePageSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomePageSectionsResponse.ProtoReflect.Descriptor instead.
func (*GetHomePageSectionsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *GetHomePageSectionsResponse) GetSections() []*HomePageSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type HomePageSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionType   SectionType            `protobuf:"varint,1,opt,name=section_type,json=sectionType,proto3,enum=recommendation.v1.SectionType" json:"section_type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // Display title, e.g. "Because you watched Inception"
	Items         []*RecommendedItem     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomePageSection) Reset() {
	*x = HomePageSection{}
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomePageSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomePageSection) ProtoMessage() {}

func (x *HomePageSection) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_recommendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomePageSection.ProtoReflect.Descriptor instead.
func (*HomePageSection) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{8}
}

func (x *HomePageSection) GetSectionType() SectionType {
	if x != nil {
		return x.SectionType
	}
	return SectionType_SECTION_TYPE_UNSPECIFIED
}

func (x *HomePageSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomePageSection) GetItems() []*RecommendedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"&recommendation/v1/recommendation.proto\x12\x11recommendation.v1\x1a\x16common/v1/common.proto\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x1aGetRecommendationsResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".recommendation.v1.RecommendedItemR\x05items\"\xbc\x02\n" +
	"\x0fRecommendedItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x129\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12%\n" +
	"\x0eaverage_rating\x18\x06 \x01(\x01R\raverageRating\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x1c\n" +
	"\talgorithm\x18\b \x01(\tR\talgorithm\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\"H\n" +
	"\x11GetSimilarRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x12GetSimilarResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.recommendation.v1.SimilarItemR\x05items\"\x97\x02\n" +
	"\vSimilarItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x129\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12%\n" +
	"\x0eaverage_rating\x18\x06 \x01(\x01R\raverageRating\x12)\n" +
	"\x10similarity_score\x18\a \x01(\x01R\x0fsimilarityScore\"5\n" +
	"\x1aGetHomePageSectionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x1bGetHomePageSectionsResponse\x12>\n" +
	"\bsections\x18\x01 \x03(\v2\".recommendation.v1.HomePageSectionR\bsections\"\xa4\x01\n" +
	"\x0fHomePageSection\x12A\n" +
	"\fsection_type\x18\x01 \x01(\x0e2\x1e.recommendation.v1.SectionTypeR\vsectionType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x128\n" +
	"\x05items\x18\x03 \x03(\v2\".recommendation.v1.RecommendedItemR\x05items*\xb5\x01\n" +
	"\vSectionType\x12\x1c\n" +
	"\x18SECTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SECTION_TYPE_PERSONAL\x10\x01\x12\x19\n" +
	"\x15SECTION_TYPE_TRENDING\x10\x02\x12$\n" +
	" SECTION_TYPE_BECAUSE_YOU_WATCHED\x10\x03\x12\x16\n" +
	"\x12SECTION_TYPE_GENRE\x10\x04\x12\x14\n" +
	"\x10SECTION_TYPE_NEW\x10\x052\xdb\x02\n" +
	"\x15RecommendationService\x12q\n" +
	"\x12GetRecommendations\x12,.recommendation.v1.GetRecommendationsRequest\x1a-.recommendation.v1.GetRecommendationsResponse\x12Y\n" +
	"\n" +
	"GetSimilar\x12$.recommendation.v1.GetSimilarRequest\x1a%.recommendation.v1.GetSimilarResponse\x12t\n" +
	"\x13GetHomePageSections\x12-.recommendation.v1.GetHomePageSectionsRequest\x1a..recommendation.v1.GetHomePageSectionsResponseBoZGgithub.com/streamvault/gateway/proto/recommendation/v1;recommendationv1\xaa\x02#StreamVault.Proto.Recommendation.V1b\x06proto3"

var (
	file_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_v1_recommendation_proto_rawDesc), len(file_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_recommendation_v1_recommendation_proto_rawDescData
}

var file_recommendation_v1_recommendation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_recommendation_v1_recommendation_proto_goTypes = []any{
	(SectionType)(0),                    // 0: recommendation.v1.SectionType
	(*GetRecommendationsRequest)(nil),   // 1: recommendation.v1.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil),  // 2: recommendation.v1.GetRecommendationsResponse
	(*RecommendedItem)(nil),             // 3: recommendation.v1.RecommendedItem
	(*GetSimilarRequest)(nil),           // 4: recommendation.v1.GetSimilarRequest
	(*GetSimilarResponse)(nil),          // 5: recommendation.v1.GetSimilarResponse
	(*SimilarItem)(nil),                 // 6: recommendation.v1.SimilarItem
	(*GetHomePageSectionsRequest)(nil),  // 7: recommendation.v1.GetHomePageSectionsRequest
	(*GetHomePageSectionsResponse)(nil), // 8: recommendation.v1.GetHomePageSectionsResponse
	(*HomePageSection)(nil),             // 9: recommendation.v1.HomePageSection
	(v1.ContentType)(0),                 // 10: common.v1.ContentType
}
var file_recommendation_v1_recommendation_proto_depIdxs = []int32{
	3,  // 0: recommendation.v1.GetRecommendationsResponse.items:type_name -> recommendation.v1.RecommendedItem
	10, // 1: recommendation.v1.RecommendedItem.content_type:type_name -> common.v1.ContentType
	6,  // 2: recommendation.v1.GetSimilarResponse.items:type_name -> recommendation.v1.SimilarItem
	10, // 3: recommendation.v1.SimilarItem.content_type:type_name -> common.v1.ContentType
	9,  // 4: recommendation.v1.GetHomePageSectionsResponse.sections:type_name -> recommendation.v1.HomePageSection
	0,  // 5: recommendation.v1.HomePageSection.section_type:type_name -> recommendation.v1.SectionType
	3,  // 6: recommendation.v1.HomePageSection.items:type_name -> recommendation.v1.RecommendedItem
	1,  // 7: recommendation.v1.RecommendationService.GetRecommendations:input_type -> recommendation.v1.GetRecommendationsRequest
	4,  // 8: recommendation.v1.RecommendationService.GetSimilar:input_type -> recommendation.v1.GetSimilarRequest
	7,  // 9: recommendation.v1.RecommendationService.GetHomePageSections:input_type -> recommendation.v1.GetHomePageSectionsRequest
	2,  // 10: recommendation.v1.RecommendationService.GetRecommendations:output_type -> recommendation.v1.GetRecommendationsResponse
	5,  // 11: recommendation.v1.RecommendationService.GetSimilar:output_type -> recommendation.v1.GetSimilarResponse
	8,  // 12: recommendation.v1.RecommendationService.GetHomePageSections:output_type -> recommendation.v1.GetHomePageSectionsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_recommendation_v1_recommendation_proto_init() }
func file_recommendation_v1_recommendation_proto_init() {
	if File_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_v1_recommendation_proto_rawDesc), len(file_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_v1_recommendation_proto_depIdxs,
		EnumInfos:         file_recommendation_v1_recommendation_proto_enumTypes,
		MessageInfos:      file_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_v1_recommendation_proto = out.File
	file_recommendation_v1_recommendation_proto_goTypes = nil
	file_recommendation_v1_recommendation_proto_depIdxs = nil
}
