mod api;
mod config;
mod consul;
mod domain;
mod error;
mod grpc;
mod log_format;
mod messaging;
mod metrics;
mod pipeline;
mod storage;
mod store;
mod telemetry;

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use axum::extract::State;
use axum::http::StatusCode;
use axum::routing::get;
use axum::{Json, Router};
use serde::Serialize;
use tokio::net::TcpListener;
use tokio::sync::{oneshot, watch};
use tower_http::trace::TraceLayer;
use tracing::{error, info, warn};
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::EnvFilter;

use crate::messaging::consumer::JobConsumer;
use crate::messaging::publisher::ResultPublisher;
use crate::pipeline::orchestrator::PipelineOrchestrator;
use crate::storage::minio::MinIOClient;
use crate::storage::StorageClient;

// ── gRPC proto (generated by tonic-build) ──────────────────────────
pub mod encoding_proto {
    tonic::include_proto!("encoding.v1");
}

// ── Health check ───────────────────────────────────────────────────
#[derive(Clone)]
pub struct AppState {
    storage: Arc<dyn StorageClient>,
    config: config::Config,
    store: store::JobStore,
    rabbit_check: Arc<dyn Fn() -> bool + Send + Sync>,
    startup_ready: Arc<AtomicBool>,
}

#[derive(Serialize)]
struct HealthResponse {
    status: &'static str,
    components: HashMap<String, ComponentStatus>,
}

#[derive(Serialize)]
struct ComponentStatus {
    status: &'static str,
}

/// Liveness probe — returns 200 if the process is alive, no dependency checks.
async fn liveness_check() -> (StatusCode, Json<HealthResponse>) {
    (
        StatusCode::OK,
        Json(HealthResponse {
            status: "healthy",
            components: HashMap::new(),
        }),
    )
}

/// Readiness probe — checks MinIO, FFmpeg, and RabbitMQ availability.
async fn readiness_check(State(state): State<AppState>) -> (StatusCode, Json<HealthResponse>) {
    let mut components = HashMap::new();
    let mut all_healthy = true;

    // MinIO
    match state
        .storage
        .health_check(&state.config.minio.raw_bucket)
        .await
    {
        Ok(_) => {
            components.insert("minio".into(), ComponentStatus { status: "healthy" });
        }
        Err(e) => {
            warn!(error = %e, "minio health check failed");
            components.insert("minio".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    // FFmpeg
    match tokio::process::Command::new(&state.config.encoding.ffmpeg_path)
        .arg("-version")
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            components.insert("ffmpeg".into(), ComponentStatus { status: "healthy" });
        }
        _ => {
            warn!("ffmpeg not available");
            components.insert("ffmpeg".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    // RabbitMQ
    if (state.rabbit_check)() {
        components.insert("rabbitmq".into(), ComponentStatus { status: "healthy" });
    } else {
        warn!("rabbitmq health check failed");
        components.insert("rabbitmq".into(), ComponentStatus { status: "unhealthy" });
        all_healthy = false;
    }

    let status_code = if all_healthy {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };

    (
        status_code,
        Json(HealthResponse {
            status: if all_healthy { "healthy" } else { "unhealthy" },
            components,
        }),
    )
}

/// Startup probe — returns 200 once initialization is complete.
async fn startup_check(State(state): State<AppState>) -> (StatusCode, Json<HealthResponse>) {
    if state.startup_ready.load(Ordering::Relaxed) {
        (
            StatusCode::OK,
            Json(HealthResponse {
                status: "healthy",
                components: HashMap::new(),
            }),
        )
    } else {
        (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(HealthResponse {
                status: "starting",
                components: HashMap::new(),
            }),
        )
    }
}

// ── Main ───────────────────────────────────────────────────────────
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cfg = config::load()?;

    let otel_provider = telemetry::init_tracer(&cfg.telemetry);
    setup_tracing(&cfg.logging, otel_provider.as_ref(), &cfg.telemetry.service_name);

    if otel_provider.is_some() {
        info!(
            endpoint = %cfg.telemetry.endpoint,
            service_name = %cfg.telemetry.service_name,
            "opentelemetry tracing initialized"
        );
    }

    info!(
        http_port = cfg.server.http_port,
        grpc_port = cfg.server.grpc_port,
        "starting encoding service"
    );

    // Create temp directory
    tokio::fs::create_dir_all(&cfg.encoding.temp_dir).await?;

    // Storage
    let storage: Arc<dyn StorageClient> = Arc::new(MinIOClient::new(&cfg.minio).await?);

    // RabbitMQ publisher
    let rabbit_publisher = Arc::new(
        messaging::publisher::RabbitMQPublisher::new(cfg.rabbitmq.clone()).await?,
    );
    let rabbit_pub_health = Arc::clone(&rabbit_publisher);
    let rabbit_check: Arc<dyn Fn() -> bool + Send + Sync> =
        Arc::new(move || rabbit_pub_health.connection().status().connected());
    let rabbit_pub_shutdown = Arc::clone(&rabbit_publisher);
    let publisher: Arc<dyn ResultPublisher> = rabbit_publisher;
    info!("rabbitmq publisher initialized");

    // Shutdown channel
    let (shutdown_tx, shutdown_rx) = watch::channel(false);

    // Job store (shared between pipeline, HTTP API, and gRPC)
    let job_store = store::new_job_store();

    // Pipeline orchestrator
    let orchestrator = PipelineOrchestrator::new(
        &cfg.encoding,
        &cfg.minio,
        Arc::clone(&storage),
        Arc::clone(&publisher),
        Arc::clone(&job_store),
    );

    // RabbitMQ consumer
    let mut consumer = JobConsumer::new(cfg.rabbitmq.clone(), Arc::new(orchestrator), shutdown_rx);

    let consumer_handle = tokio::spawn(async move {
        consumer.start().await;
    });

    // Consul registration
    let consul_client = match consul::ConsulClient::new(&cfg.consul.address) {
        Ok(mut client) => {
            if let Err(e) = client.register(&cfg.consul, cfg.server.http_port).await {
                warn!(error = %e, "failed to register with consul");
            }
            Some(client)
        }
        Err(e) => {
            warn!(error = %e, "consul unavailable, service discovery disabled");
            None
        }
    };

    // gRPC service (clone store before moving into spawned task)
    let grpc_store = Arc::clone(&job_store);

    // HTTP server
    let startup_ready = Arc::new(AtomicBool::new(false));
    let app_state = AppState {
        storage: Arc::clone(&storage),
        config: cfg.clone(),
        store: Arc::clone(&job_store),
        rabbit_check,
        startup_ready: Arc::clone(&startup_ready),
    };

    let app = Router::new()
        .route("/health", get(liveness_check))
        .route("/health/live", get(liveness_check))
        .route("/health/ready", get(readiness_check))
        .route("/health/startup", get(startup_check))
        .route("/metrics", get(metrics::metrics_handler))
        .merge(api::routes::encoding_routes())
        .layer(axum::middleware::from_fn(metrics::metrics_middleware))
        .layer(TraceLayer::new_for_http())
        .with_state(app_state);

    let http_addr = format!("0.0.0.0:{}", cfg.server.http_port);
    let http_listener = TcpListener::bind(&http_addr).await?;
    info!(addr = %http_addr, "http server listening");

    let (http_shutdown_tx, http_shutdown_rx) = oneshot::channel::<()>();
    let http_handle = tokio::spawn(async move {
        if let Err(e) = axum::serve(http_listener, app)
            .with_graceful_shutdown(async { let _ = http_shutdown_rx.await; })
            .await
        {
            error!(error = %e, "http server error");
        }
    });

    // gRPC server
    let grpc_addr = format!("0.0.0.0:{}", cfg.server.grpc_port);
    let grpc_addr_parsed: std::net::SocketAddr = grpc_addr.parse()?;
    info!(addr = %grpc_addr, "grpc server listening");

    let (grpc_shutdown_tx, grpc_shutdown_rx) = oneshot::channel::<()>();
    let grpc_handle = tokio::spawn(async move {
        let service = grpc::EncodingGrpcService::new(grpc_store);
        if let Err(e) = tonic::transport::Server::builder()
            .add_service(
                encoding_proto::encoding_service_server::EncodingServiceServer::new(service),
            )
            .serve_with_shutdown(grpc_addr_parsed, async { let _ = grpc_shutdown_rx.await; })
            .await
        {
            error!(error = %e, "grpc server error");
        }
    });

    // Mark startup complete
    startup_ready.store(true, Ordering::Relaxed);
    info!("encoding service startup complete");

    // Wait for shutdown signal (Ctrl+C or SIGTERM)
    shutdown_signal().await;
    info!("shutdown signal received, starting graceful shutdown");

    // 1. Deregister from Consul first — stop receiving new routed requests
    if let Some(client) = &consul_client {
        client.deregister().await;
    }

    // 2. Signal consumer to stop accepting new jobs
    let _ = shutdown_tx.send(true);

    // 3. Signal HTTP and gRPC servers to stop accepting new connections
    let _ = http_shutdown_tx.send(());
    let _ = grpc_shutdown_tx.send(());

    // 4. Wait for consumer to finish current job (60s timeout for encoding)
    tokio::select! {
        _ = consumer_handle => info!("consumer stopped"),
        _ = tokio::time::sleep(std::time::Duration::from_secs(60)) => {
            warn!("consumer shutdown timed out after 60s, unacked messages will be requeued");
        }
    }

    // 5. Wait for HTTP server to finish draining
    tokio::select! {
        _ = http_handle => info!("http server stopped"),
        _ = tokio::time::sleep(std::time::Duration::from_secs(5)) => {
            warn!("http server shutdown timed out");
        }
    }

    // 6. Wait for gRPC server to finish draining
    tokio::select! {
        _ = grpc_handle => info!("grpc server stopped"),
        _ = tokio::time::sleep(std::time::Duration::from_secs(5)) => {
            warn!("grpc server shutdown timed out");
        }
    }

    // 7. Close RabbitMQ publisher connection
    rabbit_pub_shutdown.close().await;

    // 8. Shutdown OpenTelemetry
    if let Some(provider) = otel_provider {
        if let Err(e) = provider.shutdown() {
            error!(error = %e, "error shutting down OTel tracer provider");
        }
    }

    info!("encoding service stopped");
    Ok(())
}

/// Waits for either Ctrl+C or SIGTERM signal.
async fn shutdown_signal() {
    let ctrl_c = tokio::signal::ctrl_c();

    #[cfg(unix)]
    {
        let mut sigterm = tokio::signal::unix::signal(
            tokio::signal::unix::SignalKind::terminate(),
        )
        .expect("failed to install SIGTERM handler");
        tokio::select! {
            _ = ctrl_c => {}
            _ = sigterm.recv() => {}
        }
    }

    #[cfg(not(unix))]
    {
        ctrl_c.await.ok();
    }
}

fn setup_tracing(
    log_config: &config::LoggingConfig,
    otel_provider: Option<&opentelemetry_sdk::trace::TracerProvider>,
    service_name: &str,
) {
    let env_filter = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new(&log_config.level))
        .unwrap_or_else(|_| EnvFilter::new("info"));

    match log_config.format.as_str() {
        "pretty" => {
            let otel_layer = otel_provider.map(|p| telemetry::create_otel_layer(p));
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().pretty())
                .with(otel_layer)
                .init();
        }
        _ => {
            let otel_layer = otel_provider.map(|p| telemetry::create_otel_layer(p));
            tracing_subscriber::registry()
                .with(env_filter)
                .with(
                    tracing_subscriber::fmt::layer()
                        .event_format(log_format::ServiceJsonFormat::new(service_name)),
                )
                .with(otel_layer)
                .init();
        }
    }
}
