mod api;
mod config;
mod consul;
mod domain;
mod error;
mod grpc;
mod messaging;
mod metrics;
mod pipeline;
mod storage;
mod store;
mod telemetry;

use std::collections::HashMap;
use std::sync::Arc;

use axum::extract::State;
use axum::http::StatusCode;
use axum::routing::get;
use axum::{Json, Router};
use serde::Serialize;
use tokio::net::TcpListener;
use tokio::sync::watch;
use tower_http::trace::TraceLayer;
use tracing::{error, info, warn};
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::EnvFilter;

use crate::messaging::consumer::JobConsumer;
use crate::messaging::publisher::ResultPublisher;
use crate::pipeline::orchestrator::PipelineOrchestrator;
use crate::storage::minio::MinIOClient;
use crate::storage::StorageClient;

// ── gRPC proto (generated by tonic-build) ──────────────────────────
pub mod encoding_proto {
    tonic::include_proto!("encoding.v1");
}

// ── Health check ───────────────────────────────────────────────────
#[derive(Clone)]
pub struct AppState {
    storage: Arc<dyn StorageClient>,
    config: config::Config,
    store: store::JobStore,
}

#[derive(Serialize)]
struct HealthResponse {
    status: &'static str,
    components: HashMap<String, ComponentStatus>,
}

#[derive(Serialize)]
struct ComponentStatus {
    status: &'static str,
}

/// Liveness probe — returns 200 if the process is alive, no dependency checks.
async fn liveness_check() -> (StatusCode, Json<HealthResponse>) {
    (
        StatusCode::OK,
        Json(HealthResponse {
            status: "healthy",
            components: HashMap::new(),
        }),
    )
}

/// Readiness probe — checks MinIO and FFmpeg availability.
async fn readiness_check(State(state): State<AppState>) -> (StatusCode, Json<HealthResponse>) {
    let mut components = HashMap::new();
    let mut all_healthy = true;

    // MinIO
    match state
        .storage
        .health_check(&state.config.minio.raw_bucket)
        .await
    {
        Ok(_) => {
            components.insert("minio".into(), ComponentStatus { status: "healthy" });
        }
        Err(e) => {
            warn!(error = %e, "minio health check failed");
            components.insert("minio".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    // FFmpeg
    match tokio::process::Command::new(&state.config.encoding.ffmpeg_path)
        .arg("-version")
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            components.insert("ffmpeg".into(), ComponentStatus { status: "healthy" });
        }
        _ => {
            warn!("ffmpeg not available");
            components.insert("ffmpeg".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    let status_code = if all_healthy {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };

    (
        status_code,
        Json(HealthResponse {
            status: if all_healthy { "healthy" } else { "unhealthy" },
            components,
        }),
    )
}

// ── Main ───────────────────────────────────────────────────────────
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cfg = config::load()?;

    let otel_provider = telemetry::init_tracer(&cfg.telemetry);
    setup_tracing(&cfg.logging, otel_provider.as_ref());

    if otel_provider.is_some() {
        info!(
            endpoint = %cfg.telemetry.endpoint,
            service_name = %cfg.telemetry.service_name,
            "opentelemetry tracing initialized"
        );
    }

    info!(
        http_port = cfg.server.http_port,
        grpc_port = cfg.server.grpc_port,
        "starting encoding service"
    );

    // Create temp directory
    tokio::fs::create_dir_all(&cfg.encoding.temp_dir).await?;

    // Storage
    let storage: Arc<dyn StorageClient> = Arc::new(MinIOClient::new(&cfg.minio).await?);

    // RabbitMQ publisher
    let publisher: Arc<dyn ResultPublisher> = Arc::new(
        messaging::publisher::RabbitMQPublisher::new(cfg.rabbitmq.clone()).await?,
    );
    info!("rabbitmq publisher initialized");

    // Shutdown channel
    let (shutdown_tx, shutdown_rx) = watch::channel(false);

    // Job store (shared between pipeline, HTTP API, and gRPC)
    let job_store = store::new_job_store();

    // Pipeline orchestrator
    let orchestrator = PipelineOrchestrator::new(
        &cfg.encoding,
        &cfg.minio,
        Arc::clone(&storage),
        Arc::clone(&publisher),
        Arc::clone(&job_store),
    );

    // RabbitMQ consumer
    let mut consumer = JobConsumer::new(cfg.rabbitmq.clone(), Arc::new(orchestrator), shutdown_rx);

    let consumer_handle = tokio::spawn(async move {
        consumer.start().await;
    });

    // Consul registration
    let consul_client = match consul::ConsulClient::new(&cfg.consul.address) {
        Ok(mut client) => {
            if let Err(e) = client.register(&cfg.consul, cfg.server.http_port).await {
                warn!(error = %e, "failed to register with consul");
            }
            Some(client)
        }
        Err(e) => {
            warn!(error = %e, "consul unavailable, service discovery disabled");
            None
        }
    };

    // gRPC service (clone store before moving into spawned task)
    let grpc_store = Arc::clone(&job_store);

    // HTTP server
    let app_state = AppState {
        storage: Arc::clone(&storage),
        config: cfg.clone(),
        store: Arc::clone(&job_store),
    };

    let app = Router::new()
        .route("/health", get(liveness_check))
        .route("/health/live", get(liveness_check))
        .route("/health/ready", get(readiness_check))
        .route("/metrics", get(metrics::metrics_handler))
        .merge(api::routes::encoding_routes())
        .layer(axum::middleware::from_fn(metrics::metrics_middleware))
        .layer(TraceLayer::new_for_http())
        .with_state(app_state);

    let http_addr = format!("0.0.0.0:{}", cfg.server.http_port);
    let http_listener = TcpListener::bind(&http_addr).await?;
    info!(addr = %http_addr, "http server listening");

    let http_handle = tokio::spawn(async move {
        if let Err(e) = axum::serve(http_listener, app).await {
            error!(error = %e, "http server error");
        }
    });

    // gRPC server
    let grpc_addr = format!("0.0.0.0:{}", cfg.server.grpc_port);
    let grpc_addr_parsed: std::net::SocketAddr = grpc_addr.parse()?;
    info!(addr = %grpc_addr, "grpc server listening");

    let grpc_handle = tokio::spawn(async move {
        let service = grpc::EncodingGrpcService::new(grpc_store);
        if let Err(e) = tonic::transport::Server::builder()
            .add_service(
                encoding_proto::encoding_service_server::EncodingServiceServer::new(service),
            )
            .serve(grpc_addr_parsed)
            .await
        {
            error!(error = %e, "grpc server error");
        }
    });

    // Wait for shutdown signal
    tokio::signal::ctrl_c().await?;
    info!("shutdown signal received");

    // Graceful shutdown
    let _ = shutdown_tx.send(true);

    tokio::select! {
        _ = consumer_handle => info!("consumer stopped"),
        _ = tokio::time::sleep(std::time::Duration::from_secs(30)) => {
            warn!("consumer shutdown timed out");
        }
    }

    http_handle.abort();
    grpc_handle.abort();

    if let Some(client) = &consul_client {
        client.deregister().await;
    }

    if let Some(provider) = otel_provider {
        if let Err(e) = provider.shutdown() {
            error!(error = %e, "error shutting down OTel tracer provider");
        }
    }

    info!("encoding service stopped");
    Ok(())
}

fn setup_tracing(
    log_config: &config::LoggingConfig,
    otel_provider: Option<&opentelemetry_sdk::trace::TracerProvider>,
) {
    let env_filter = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new(&log_config.level))
        .unwrap_or_else(|_| EnvFilter::new("info"));

    match log_config.format.as_str() {
        "pretty" => {
            let otel_layer = otel_provider.map(|p| telemetry::create_otel_layer(p));
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().pretty())
                .with(otel_layer)
                .init();
        }
        _ => {
            let otel_layer = otel_provider.map(|p| telemetry::create_otel_layer(p));
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().json())
                .with(otel_layer)
                .init();
        }
    }
}
