#![allow(dead_code)] // Part 2 will use all declared items

mod config;
mod consul;
mod domain;
mod error;
mod messaging;
mod storage;

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use axum::extract::State;
use axum::http::StatusCode;
use axum::routing::get;
use axum::{Json, Router};
use serde::Serialize;
use tokio::net::TcpListener;
use tokio::sync::watch;
use tower_http::trace::TraceLayer;
use tracing::{error, info, warn};
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::EnvFilter;

use crate::messaging::consumer::{JobConsumer, JobProcessor};
use crate::messaging::models::EncodingJob;
use crate::storage::minio::MinIOClient;
use crate::storage::StorageClient;

// ── gRPC proto (generated by tonic-build) ──────────────────────────
pub mod encoding_proto {
    tonic::include_proto!("encoding.v1");
}

// ── Stub job processor (Part 2 will replace with actual pipeline) ──
struct StubJobProcessor;

#[async_trait]
impl JobProcessor for StubJobProcessor {
    async fn process(&self, job: EncodingJob) -> error::Result<()> {
        info!(
            job_id = %job.job_id,
            content_id = %job.content_id,
            source = %job.source_path,
            "received job (stub processor — pipeline not yet implemented)"
        );
        Ok(())
    }
}

// ── gRPC service stub ──────────────────────────────────────────────
struct EncodingGrpcService;

#[tonic::async_trait]
impl encoding_proto::encoding_service_server::EncodingService for EncodingGrpcService {
    async fn get_job_status(
        &self,
        request: tonic::Request<encoding_proto::GetJobStatusRequest>,
    ) -> std::result::Result<tonic::Response<encoding_proto::JobStatusResponse>, tonic::Status>
    {
        let job_id = &request.get_ref().job_id;
        info!(job_id, "get_job_status called (stub)");
        Err(tonic::Status::unimplemented(
            "will be implemented in Part 2",
        ))
    }

    async fn list_jobs(
        &self,
        _request: tonic::Request<encoding_proto::ListJobsRequest>,
    ) -> std::result::Result<tonic::Response<encoding_proto::ListJobsResponse>, tonic::Status>
    {
        info!("list_jobs called (stub)");
        Err(tonic::Status::unimplemented(
            "will be implemented in Part 2",
        ))
    }
}

// ── Health check ───────────────────────────────────────────────────
#[derive(Clone)]
struct AppState {
    storage: Arc<dyn StorageClient>,
    config: config::Config,
}

#[derive(Serialize)]
struct HealthResponse {
    status: &'static str,
    components: HashMap<String, ComponentStatus>,
}

#[derive(Serialize)]
struct ComponentStatus {
    status: &'static str,
}

async fn health_check(State(state): State<AppState>) -> (StatusCode, Json<HealthResponse>) {
    let mut components = HashMap::new();
    let mut all_healthy = true;

    // MinIO
    match state
        .storage
        .health_check(&state.config.minio.raw_bucket)
        .await
    {
        Ok(_) => {
            components.insert("minio".into(), ComponentStatus { status: "healthy" });
        }
        Err(e) => {
            warn!(error = %e, "minio health check failed");
            components.insert("minio".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    // FFmpeg
    match tokio::process::Command::new(&state.config.encoding.ffmpeg_path)
        .arg("-version")
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            components.insert("ffmpeg".into(), ComponentStatus { status: "healthy" });
        }
        _ => {
            warn!("ffmpeg not available");
            components.insert("ffmpeg".into(), ComponentStatus { status: "unhealthy" });
            all_healthy = false;
        }
    }

    let status_code = if all_healthy {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };

    (
        status_code,
        Json(HealthResponse {
            status: if all_healthy { "healthy" } else { "unhealthy" },
            components,
        }),
    )
}

// ── Main ───────────────────────────────────────────────────────────
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cfg = config::load()?;
    setup_logging(&cfg.logging);

    info!(
        http_port = cfg.server.http_port,
        grpc_port = cfg.server.grpc_port,
        "starting encoding service"
    );

    // Create temp directory
    tokio::fs::create_dir_all(&cfg.encoding.temp_dir).await?;

    // Storage
    let storage: Arc<dyn StorageClient> = Arc::new(MinIOClient::new(&cfg.minio).await?);

    // RabbitMQ publisher
    let publisher = Arc::new(
        messaging::publisher::RabbitMQPublisher::new(cfg.rabbitmq.clone()).await?,
    );
    info!("rabbitmq publisher initialized");

    // Shutdown channel
    let (shutdown_tx, shutdown_rx) = watch::channel(false);

    // RabbitMQ consumer
    let processor: Arc<dyn JobProcessor> = Arc::new(StubJobProcessor);
    let mut consumer = JobConsumer::new(cfg.rabbitmq.clone(), processor, shutdown_rx);

    let consumer_handle = tokio::spawn(async move {
        consumer.start().await;
    });

    // Consul registration
    let consul_client = match consul::ConsulClient::new(&cfg.consul.address) {
        Ok(mut client) => {
            if let Err(e) = client.register(&cfg.consul, cfg.server.http_port).await {
                warn!(error = %e, "failed to register with consul");
            }
            Some(client)
        }
        Err(e) => {
            warn!(error = %e, "consul unavailable, service discovery disabled");
            None
        }
    };

    // HTTP server
    let app_state = AppState {
        storage: Arc::clone(&storage),
        config: cfg.clone(),
    };

    let app = Router::new()
        .route("/health", get(health_check))
        .layer(TraceLayer::new_for_http())
        .with_state(app_state);

    let http_addr = format!("0.0.0.0:{}", cfg.server.http_port);
    let http_listener = TcpListener::bind(&http_addr).await?;
    info!(addr = %http_addr, "http server listening");

    let http_handle = tokio::spawn(async move {
        if let Err(e) = axum::serve(http_listener, app).await {
            error!(error = %e, "http server error");
        }
    });

    // gRPC server
    let grpc_addr = format!("0.0.0.0:{}", cfg.server.grpc_port);
    let grpc_addr_parsed: std::net::SocketAddr = grpc_addr.parse()?;
    info!(addr = %grpc_addr, "grpc server listening");

    let grpc_handle = tokio::spawn(async move {
        let service = EncodingGrpcService;
        if let Err(e) = tonic::transport::Server::builder()
            .add_service(
                encoding_proto::encoding_service_server::EncodingServiceServer::new(service),
            )
            .serve(grpc_addr_parsed)
            .await
        {
            error!(error = %e, "grpc server error");
        }
    });

    // Keep publisher alive
    let _publisher = publisher;

    // Wait for shutdown signal
    tokio::signal::ctrl_c().await?;
    info!("shutdown signal received");

    // Graceful shutdown
    let _ = shutdown_tx.send(true);

    tokio::select! {
        _ = consumer_handle => info!("consumer stopped"),
        _ = tokio::time::sleep(std::time::Duration::from_secs(30)) => {
            warn!("consumer shutdown timed out");
        }
    }

    http_handle.abort();
    grpc_handle.abort();

    if let Some(client) = &consul_client {
        client.deregister().await;
    }

    info!("encoding service stopped");
    Ok(())
}

fn setup_logging(config: &config::LoggingConfig) {
    let env_filter = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new(&config.level))
        .unwrap_or_else(|_| EnvFilter::new("info"));

    match config.format.as_str() {
        "pretty" => {
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().pretty())
                .init();
        }
        _ => {
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().json())
                .init();
        }
    }
}
