// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentByIdRequest) Reset() {
	*x = GetContentByIdRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentByIdRequest) ProtoMessage() {}

func (x *GetContentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentByIdRequest.ProtoReflect.Descriptor instead.
func (*GetContentByIdRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetContentByIdRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type ContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,6,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentResponse) Reset() {
	*x = ContentResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResponse) ProtoMessage() {}

func (x *ContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResponse.ProtoReflect.Descriptor instead.
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ContentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContentResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ContentResponse) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *ContentResponse) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

type GetContentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentIds    []string               `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentListRequest) Reset() {
	*x = GetContentListRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentListRequest) ProtoMessage() {}

func (x *GetContentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentListRequest.ProtoReflect.Descriptor instead.
func (*GetContentListRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentListRequest) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type ContentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContentResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentListResponse) Reset() {
	*x = ContentListResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentListResponse) ProtoMessage() {}

func (x *ContentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentListResponse.ProtoReflect.Descriptor instead.
func (*ContentListResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ContentListResponse) GetItems() []*ContentResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"6\n" +
	"\x15GetContentByIdRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\xc4\x01\n" +
	"\x0fContentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12!\n" +
	"\frelease_year\x18\x06 \x01(\x05R\vreleaseYear\"8\n" +
	"\x15GetContentListRequest\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\"H\n" +
	"\x13ContentListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.catalog.v1.ContentResponseR\x05items2\xb8\x01\n" +
	"\x0eCatalogService\x12P\n" +
	"\x0eGetContentById\x12!.catalog.v1.GetContentByIdRequest\x1a\x1b.catalog.v1.ContentResponse\x12T\n" +
	"\x0eGetContentList\x12!.catalog.v1.GetContentListRequest\x1a\x1f.catalog.v1.ContentListResponseBZZ9github.com/streamvault/gateway/proto/catalog/v1;catalogv1\xaa\x02\x1cStreamVault.Proto.Catalog.V1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*GetContentByIdRequest)(nil), // 0: catalog.v1.GetContentByIdRequest
	(*ContentResponse)(nil),       // 1: catalog.v1.ContentResponse
	(*GetContentListRequest)(nil), // 2: catalog.v1.GetContentListRequest
	(*ContentListResponse)(nil),   // 3: catalog.v1.ContentListResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	1, // 0: catalog.v1.ContentListResponse.items:type_name -> catalog.v1.ContentResponse
	0, // 1: catalog.v1.CatalogService.GetContentById:input_type -> catalog.v1.GetContentByIdRequest
	2, // 2: catalog.v1.CatalogService.GetContentList:input_type -> catalog.v1.GetContentListRequest
	1, // 3: catalog.v1.CatalogService.GetContentById:output_type -> catalog.v1.ContentResponse
	3, // 4: catalog.v1.CatalogService.GetContentList:output_type -> catalog.v1.ContentListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
