// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: search/v1/search.proto

package searchv1

import (
	v1 "github.com/streamvault/gateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortField defines the available sort options for search results.
type SortField int32

const (
	SortField_SORT_FIELD_UNSPECIFIED SortField = 0
	SortField_SORT_FIELD_RELEVANCE   SortField = 1
	SortField_SORT_FIELD_RATING      SortField = 2
	SortField_SORT_FIELD_YEAR        SortField = 3
	SortField_SORT_FIELD_TITLE       SortField = 4
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_FIELD_UNSPECIFIED",
		1: "SORT_FIELD_RELEVANCE",
		2: "SORT_FIELD_RATING",
		3: "SORT_FIELD_YEAR",
		4: "SORT_FIELD_TITLE",
	}
	SortField_value = map[string]int32{
		"SORT_FIELD_UNSPECIFIED": 0,
		"SORT_FIELD_RELEVANCE":   1,
		"SORT_FIELD_RATING":      2,
		"SORT_FIELD_YEAR":        3,
		"SORT_FIELD_TITLE":       4,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_search_v1_search_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_search_v1_search_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

// SortOrder defines ascending or descending sort direction.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_search_v1_search_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_search_v1_search_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

// TimeWindow defines the period for trending content.
type TimeWindow int32

const (
	TimeWindow_TIME_WINDOW_UNSPECIFIED TimeWindow = 0
	TimeWindow_TIME_WINDOW_DAY         TimeWindow = 1
	TimeWindow_TIME_WINDOW_WEEK        TimeWindow = 2
	TimeWindow_TIME_WINDOW_MONTH       TimeWindow = 3
)

// Enum value maps for TimeWindow.
var (
	TimeWindow_name = map[int32]string{
		0: "TIME_WINDOW_UNSPECIFIED",
		1: "TIME_WINDOW_DAY",
		2: "TIME_WINDOW_WEEK",
		3: "TIME_WINDOW_MONTH",
	}
	TimeWindow_value = map[string]int32{
		"TIME_WINDOW_UNSPECIFIED": 0,
		"TIME_WINDOW_DAY":         1,
		"TIME_WINDOW_WEEK":        2,
		"TIME_WINDOW_MONTH":       3,
	}
)

func (x TimeWindow) Enum() *TimeWindow {
	p := new(TimeWindow)
	*p = x
	return p
}

func (x TimeWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_search_v1_search_proto_enumTypes[2].Descriptor()
}

func (TimeWindow) Type() protoreflect.EnumType {
	return &file_search_v1_search_proto_enumTypes[2]
}

func (x TimeWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeWindow.Descriptor instead.
func (TimeWindow) EnumDescriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Filters       *SearchFilters         `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	SortField     SortField              `protobuf:"varint,3,opt,name=sort_field,json=sortField,proto3,enum=search.v1.SortField" json:"sort_field,omitempty"`
	SortOrder     SortOrder              `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=search.v1.SortOrder" json:"sort_order,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFilters() *SearchFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetSortField() SortField {
	if x != nil {
		return x.SortField
	}
	return SortField_SORT_FIELD_UNSPECIFIED
}

func (x *SearchRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *SearchRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchFilters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Genres          []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	YearFrom        int32                  `protobuf:"varint,2,opt,name=year_from,json=yearFrom,proto3" json:"year_from,omitempty"`                                     // 0 = no lower bound
	YearTo          int32                  `protobuf:"varint,3,opt,name=year_to,json=yearTo,proto3" json:"year_to,omitempty"`                                           // 0 = no upper bound
	MaturityRatings []string               `protobuf:"bytes,4,rep,name=maturity_ratings,json=maturityRatings,proto3" json:"maturity_ratings,omitempty"`                 // "G", "PG", "PG13", "R", "NC17"
	MinRating       float64                `protobuf:"fixed64,5,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`                                 // 0.0 = no minimum
	ContentType     v1.ContentType         `protobuf:"varint,6,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"` // UNSPECIFIED = all types
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchFilters) Reset() {
	*x = SearchFilters{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilters) ProtoMessage() {}

func (x *SearchFilters) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilters.ProtoReflect.Descriptor instead.
func (*SearchFilters) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFilters) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *SearchFilters) GetYearFrom() int32 {
	if x != nil {
		return x.YearFrom
	}
	return 0
}

func (x *SearchFilters) GetYearTo() int32 {
	if x != nil {
		return x.YearTo
	}
	return 0
}

func (x *SearchFilters) GetMaturityRatings() []string {
	if x != nil {
		return x.MaturityRatings
	}
	return nil
}

func (x *SearchFilters) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *SearchFilters) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Facets        *Facets                `protobuf:"bytes,2,opt,name=facets,proto3" json:"facets,omitempty"`
	Pagination    *v1.PaginatedResponse  `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetFacets() *Facets {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *SearchResponse) GetPagination() *v1.PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContentType   v1.ContentType         `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,6,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	AverageRating float64                `protobuf:"fixed64,7,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Highlights    *HighlightFields       `protobuf:"bytes,8,opt,name=highlights,proto3" json:"highlights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchHit) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchHit) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

func (x *SearchHit) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *SearchHit) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *SearchHit) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *SearchHit) GetHighlights() *HighlightFields {
	if x != nil {
		return x.Highlights
	}
	return nil
}

type HighlightFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`             // Title with <em> highlight tags
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Description with <em> highlight tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighlightFields) Reset() {
	*x = HighlightFields{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighlightFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightFields) ProtoMessage() {}

func (x *HighlightFields) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightFields.ProtoReflect.Descriptor instead.
func (*HighlightFields) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *HighlightFields) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HighlightFields) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Facets struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GenreFacets       []*FacetBucket         `protobuf:"bytes,1,rep,name=genre_facets,json=genreFacets,proto3" json:"genre_facets,omitempty"`
	YearFacets        []*FacetBucket         `protobuf:"bytes,2,rep,name=year_facets,json=yearFacets,proto3" json:"year_facets,omitempty"`
	MaturityFacets    []*FacetBucket         `protobuf:"bytes,3,rep,name=maturity_facets,json=maturityFacets,proto3" json:"maturity_facets,omitempty"`
	ContentTypeFacets []*FacetBucket         `protobuf:"bytes,4,rep,name=content_type_facets,json=contentTypeFacets,proto3" json:"content_type_facets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Facets) Reset() {
	*x = Facets{}
	mi := &file_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facets) ProtoMessage() {}

func (x *Facets) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facets.ProtoReflect.Descriptor instead.
func (*Facets) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *Facets) GetGenreFacets() []*FacetBucket {
	if x != nil {
		return x.GenreFacets
	}
	return nil
}

func (x *Facets) GetYearFacets() []*FacetBucket {
	if x != nil {
		return x.YearFacets
	}
	return nil
}

func (x *Facets) GetMaturityFacets() []*FacetBucket {
	if x != nil {
		return x.MaturityFacets
	}
	return nil
}

func (x *Facets) GetContentTypeFacets() []*FacetBucket {
	if x != nil {
		return x.ContentTypeFacets
	}
	return nil
}

type FacetBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DocCount      int64                  `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetBucket) Reset() {
	*x = FacetBucket{}
	mi := &file_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetBucket) ProtoMessage() {}

func (x *FacetBucket) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetBucket.ProtoReflect.Descriptor instead.
func (*FacetBucket) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *FacetBucket) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FacetBucket) GetDocCount() int64 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

type AutocompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`  // Minimum 2 characters
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max suggestions; 0 = server default (5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteRequest) Reset() {
	*x = AutocompleteRequest{}
	mi := &file_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteRequest) ProtoMessage() {}

func (x *AutocompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *AutocompleteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AutocompleteRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AutocompleteResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Suggestions   []*AutocompleteSuggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteResponse) Reset() {
	*x = AutocompleteResponse{}
	mi := &file_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteResponse) ProtoMessage() {}

func (x *AutocompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteResponse.ProtoReflect.Descriptor instead.
func (*AutocompleteResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *AutocompleteResponse) GetSuggestions() []*AutocompleteSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type AutocompleteSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentType   v1.ContentType         `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteSuggestion) Reset() {
	*x = AutocompleteSuggestion{}
	mi := &file_search_v1_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteSuggestion) ProtoMessage() {}

func (x *AutocompleteSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteSuggestion.ProtoReflect.Descriptor instead.
func (*AutocompleteSuggestion) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{9}
}

func (x *AutocompleteSuggestion) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AutocompleteSuggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AutocompleteSuggestion) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

func (x *AutocompleteSuggestion) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *AutocompleteSuggestion) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

type GetTrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeWindow    TimeWindow             `protobuf:"varint,1,opt,name=time_window,json=timeWindow,proto3,enum=search.v1.TimeWindow" json:"time_window,omitempty"` // UNSPECIFIED defaults to WEEK
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                                       // Max items; 0 = server default (20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingRequest) Reset() {
	*x = GetTrendingRequest{}
	mi := &file_search_v1_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingRequest) ProtoMessage() {}

func (x *GetTrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{10}
}

func (x *GetTrendingRequest) GetTimeWindow() TimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return TimeWindow_TIME_WINDOW_UNSPECIFIED
}

func (x *GetTrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TrendingItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingResponse) Reset() {
	*x = GetTrendingResponse{}
	mi := &file_search_v1_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingResponse) ProtoMessage() {}

func (x *GetTrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{11}
}

func (x *GetTrendingResponse) GetItems() []*TrendingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrendingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ContentType   v1.ContentType         `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=common.v1.ContentType" json:"content_type,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	AverageRating float64                `protobuf:"fixed64,6,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Rank          int32                  `protobuf:"varint,7,opt,name=rank,proto3" json:"rank,omitempty"`
	RankChange    int32                  `protobuf:"varint,8,opt,name=rank_change,json=rankChange,proto3" json:"rank_change,omitempty"` // Positive = moved up, negative = moved down
	ViewCount     int64                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingItem) Reset() {
	*x = TrendingItem{}
	mi := &file_search_v1_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingItem) ProtoMessage() {}

func (x *TrendingItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingItem.ProtoReflect.Descriptor instead.
func (*TrendingItem) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{12}
}

func (x *TrendingItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *TrendingItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrendingItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *TrendingItem) GetContentType() v1.ContentType {
	if x != nil {
		return x.ContentType
	}
	return v1.ContentType(0)
}

func (x *TrendingItem) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *TrendingItem) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *TrendingItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *TrendingItem) GetRankChange() int32 {
	if x != nil {
		return x.RankChange
	}
	return 0
}

func (x *TrendingItem) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\x1a\x16common/v1/common.proto\"\xfa\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.search.v1.SearchFiltersR\afilters\x123\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\x0e2\x14.search.v1.SortFieldR\tsortField\x123\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x14.search.v1.SortOrderR\tsortOrder\x125\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x15.common.v1.PaginationR\n" +
	"pagination\"\xe2\x01\n" +
	"\rSearchFilters\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12\x1b\n" +
	"\tyear_from\x18\x02 \x01(\x05R\byearFrom\x12\x17\n" +
	"\ayear_to\x18\x03 \x01(\x05R\x06yearTo\x12)\n" +
	"\x10maturity_ratings\x18\x04 \x03(\tR\x0fmaturityRatings\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x05 \x01(\x01R\tminRating\x129\n" +
	"\fcontent_type\x18\x06 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\"\xa3\x01\n" +
	"\x0eSearchResponse\x12(\n" +
	"\x04hits\x18\x01 \x03(\v2\x14.search.v1.SearchHitR\x04hits\x12)\n" +
	"\x06facets\x18\x02 \x01(\v2\x11.search.v1.FacetsR\x06facets\x12<\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1c.common.v1.PaginatedResponseR\n" +
	"pagination\"\xc8\x02\n" +
	"\tSearchHit\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12!\n" +
	"\frelease_year\x18\x06 \x01(\x05R\vreleaseYear\x12%\n" +
	"\x0eaverage_rating\x18\a \x01(\x01R\raverageRating\x12:\n" +
	"\n" +
	"highlights\x18\b \x01(\v2\x1a.search.v1.HighlightFieldsR\n" +
	"highlights\"I\n" +
	"\x0fHighlightFields\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x85\x02\n" +
	"\x06Facets\x129\n" +
	"\fgenre_facets\x18\x01 \x03(\v2\x16.search.v1.FacetBucketR\vgenreFacets\x127\n" +
	"\vyear_facets\x18\x02 \x03(\v2\x16.search.v1.FacetBucketR\n" +
	"yearFacets\x12?\n" +
	"\x0fmaturity_facets\x18\x03 \x03(\v2\x16.search.v1.FacetBucketR\x0ematurityFacets\x12F\n" +
	"\x13content_type_facets\x18\x04 \x03(\v2\x16.search.v1.FacetBucketR\x11contentTypeFacets\"<\n" +
	"\vFacetBucket\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tdoc_count\x18\x02 \x01(\x03R\bdocCount\"A\n" +
	"\x13AutocompleteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"[\n" +
	"\x14AutocompleteResponse\x12C\n" +
	"\vsuggestions\x18\x01 \x03(\v2!.search.v1.AutocompleteSuggestionR\vsuggestions\"\xd0\x01\n" +
	"\x16AutocompleteSuggestion\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\fcontent_type\x18\x03 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\"b\n" +
	"\x12GetTrendingRequest\x126\n" +
	"\vtime_window\x18\x01 \x01(\x0e2\x15.search.v1.TimeWindowR\n" +
	"timeWindow\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x13GetTrendingResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.search.v1.TrendingItemR\x05items\"\xc1\x02\n" +
	"\fTrendingItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x129\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x16.common.v1.ContentTypeR\vcontentType\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12%\n" +
	"\x0eaverage_rating\x18\x06 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04rank\x18\a \x01(\x05R\x04rank\x12\x1f\n" +
	"\vrank_change\x18\b \x01(\x05R\n" +
	"rankChange\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x03R\tviewCount*\x83\x01\n" +
	"\tSortField\x12\x1a\n" +
	"\x16SORT_FIELD_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SORT_FIELD_RELEVANCE\x10\x01\x12\x15\n" +
	"\x11SORT_FIELD_RATING\x10\x02\x12\x13\n" +
	"\x0fSORT_FIELD_YEAR\x10\x03\x12\x14\n" +
	"\x10SORT_FIELD_TITLE\x10\x04*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02*k\n" +
	"\n" +
	"TimeWindow\x12\x1b\n" +
	"\x17TIME_WINDOW_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTIME_WINDOW_DAY\x10\x01\x12\x14\n" +
	"\x10TIME_WINDOW_WEEK\x10\x02\x12\x15\n" +
	"\x11TIME_WINDOW_MONTH\x10\x032\xed\x01\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\x12O\n" +
	"\fAutocomplete\x12\x1e.search.v1.AutocompleteRequest\x1a\x1f.search.v1.AutocompleteResponse\x12L\n" +
	"\vGetTrending\x12\x1d.search.v1.GetTrendingRequest\x1a\x1e.search.v1.GetTrendingResponseBWZ7github.com/streamvault/gateway/proto/search/v1;searchv1\xaa\x02\x1bStreamVault.Proto.Search.V1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_search_v1_search_proto_goTypes = []any{
	(SortField)(0),                 // 0: search.v1.SortField
	(SortOrder)(0),                 // 1: search.v1.SortOrder
	(TimeWindow)(0),                // 2: search.v1.TimeWindow
	(*SearchRequest)(nil),          // 3: search.v1.SearchRequest
	(*SearchFilters)(nil),          // 4: search.v1.SearchFilters
	(*SearchResponse)(nil),         // 5: search.v1.SearchResponse
	(*SearchHit)(nil),              // 6: search.v1.SearchHit
	(*HighlightFields)(nil),        // 7: search.v1.HighlightFields
	(*Facets)(nil),                 // 8: search.v1.Facets
	(*FacetBucket)(nil),            // 9: search.v1.FacetBucket
	(*AutocompleteRequest)(nil),    // 10: search.v1.AutocompleteRequest
	(*AutocompleteResponse)(nil),   // 11: search.v1.AutocompleteResponse
	(*AutocompleteSuggestion)(nil), // 12: search.v1.AutocompleteSuggestion
	(*GetTrendingRequest)(nil),     // 13: search.v1.GetTrendingRequest
	(*GetTrendingResponse)(nil),    // 14: search.v1.GetTrendingResponse
	(*TrendingItem)(nil),           // 15: search.v1.TrendingItem
	(*v1.Pagination)(nil),          // 16: common.v1.Pagination
	(v1.ContentType)(0),            // 17: common.v1.ContentType
	(*v1.PaginatedResponse)(nil),   // 18: common.v1.PaginatedResponse
}
var file_search_v1_search_proto_depIdxs = []int32{
	4,  // 0: search.v1.SearchRequest.filters:type_name -> search.v1.SearchFilters
	0,  // 1: search.v1.SearchRequest.sort_field:type_name -> search.v1.SortField
	1,  // 2: search.v1.SearchRequest.sort_order:type_name -> search.v1.SortOrder
	16, // 3: search.v1.SearchRequest.pagination:type_name -> common.v1.Pagination
	17, // 4: search.v1.SearchFilters.content_type:type_name -> common.v1.ContentType
	6,  // 5: search.v1.SearchResponse.hits:type_name -> search.v1.SearchHit
	8,  // 6: search.v1.SearchResponse.facets:type_name -> search.v1.Facets
	18, // 7: search.v1.SearchResponse.pagination:type_name -> common.v1.PaginatedResponse
	17, // 8: search.v1.SearchHit.content_type:type_name -> common.v1.ContentType
	7,  // 9: search.v1.SearchHit.highlights:type_name -> search.v1.HighlightFields
	9,  // 10: search.v1.Facets.genre_facets:type_name -> search.v1.FacetBucket
	9,  // 11: search.v1.Facets.year_facets:type_name -> search.v1.FacetBucket
	9,  // 12: search.v1.Facets.maturity_facets:type_name -> search.v1.FacetBucket
	9,  // 13: search.v1.Facets.content_type_facets:type_name -> search.v1.FacetBucket
	12, // 14: search.v1.AutocompleteResponse.suggestions:type_name -> search.v1.AutocompleteSuggestion
	17, // 15: search.v1.AutocompleteSuggestion.content_type:type_name -> common.v1.ContentType
	2,  // 16: search.v1.GetTrendingRequest.time_window:type_name -> search.v1.TimeWindow
	15, // 17: search.v1.GetTrendingResponse.items:type_name -> search.v1.TrendingItem
	17, // 18: search.v1.TrendingItem.content_type:type_name -> common.v1.ContentType
	3,  // 19: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	10, // 20: search.v1.SearchService.Autocomplete:input_type -> search.v1.AutocompleteRequest
	13, // 21: search.v1.SearchService.GetTrending:input_type -> search.v1.GetTrendingRequest
	5,  // 22: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	11, // 23: search.v1.SearchService.Autocomplete:output_type -> search.v1.AutocompleteResponse
	14, // 24: search.v1.SearchService.GetTrending:output_type -> search.v1.GetTrendingResponse
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		EnumInfos:         file_search_v1_search_proto_enumTypes,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
