// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: encoding/v1/encoding.proto

package encodingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus tracks the lifecycle of an encoding job.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_PROCESSING  JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_PROCESSING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_PROCESSING":  2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encoding_v1_encoding_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_encoding_v1_encoding_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{0}
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_encoding_v1_encoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_v1_encoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ContentId          string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Status             JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=encoding.v1.JobStatus" json:"status,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"` // 0.0 - 100.0
	CurrentStep        string                 `protobuf:"bytes,5,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`                        // "validating", "transcoding_720p", "segmenting", etc.
	Outputs            []*EncodingOutput      `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Populated only when status is FAILED
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_encoding_v1_encoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_v1_encoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{1}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobStatusResponse) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *JobStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *JobStatusResponse) GetOutputs() []*EncodingOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *JobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// EncodingOutput describes the result of encoding to a specific quality level.
type EncodingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"` // "360p", "720p", "1080p", "4k"
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,4,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,5,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	SegmentCount  int32                  `protobuf:"varint,6,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	PlaylistPath  string                 `protobuf:"bytes,7,opt,name=playlist_path,json=playlistPath,proto3" json:"playlist_path,omitempty"` // MinIO path to quality playlist.m3u8
	StoragePath   string                 `protobuf:"bytes,8,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`    // MinIO base path for segments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodingOutput) Reset() {
	*x = EncodingOutput{}
	mi := &file_encoding_v1_encoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodingOutput) ProtoMessage() {}

func (x *EncodingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_v1_encoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodingOutput.ProtoReflect.Descriptor instead.
func (*EncodingOutput) Descriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{2}
}

func (x *EncodingOutput) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *EncodingOutput) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *EncodingOutput) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EncodingOutput) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *EncodingOutput) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *EncodingOutput) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *EncodingOutput) GetPlaylistPath() string {
	if x != nil {
		return x.PlaylistPath
	}
	return ""
}

func (x *EncodingOutput) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

type ListJobsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter    JobStatus              `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=encoding.v1.JobStatus" json:"status_filter,omitempty"` // Filter by status; UNSPECIFIED = all
	ContentIdFilter string                 `protobuf:"bytes,2,opt,name=content_id_filter,json=contentIdFilter,proto3" json:"content_id_filter,omitempty"`                  // Filter by content ID; empty = all
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                              // Max items; 0 = server default
	Offset          int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                                            // Pagination offset
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_encoding_v1_encoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_v1_encoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsRequest) GetStatusFilter() JobStatus {
	if x != nil {
		return x.StatusFilter
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetContentIdFilter() string {
	if x != nil {
		return x.ContentIdFilter
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobStatusResponse   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_encoding_v1_encoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_v1_encoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_encoding_v1_encoding_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsResponse) GetJobs() []*JobStatusResponse {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_encoding_v1_encoding_proto protoreflect.FileDescriptor

const file_encoding_v1_encoding_proto_rawDesc = "" +
	"\n" +
	"\x1aencoding/v1/encoding.proto\x12\vencoding.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xde\x03\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.encoding.v1.JobStatusR\x06status\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x01R\x12progressPercentage\x12!\n" +
	"\fcurrent_step\x18\x05 \x01(\tR\vcurrentStep\x125\n" +
	"\aoutputs\x18\x06 \x03(\v2\x1b.encoding.v1.EncodingOutputR\aoutputs\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x90\x02\n" +
	"\x0eEncodingOutput\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12!\n" +
	"\fbitrate_kbps\x18\x04 \x01(\x05R\vbitrateKbps\x12&\n" +
	"\x0ffile_size_bytes\x18\x05 \x01(\x03R\rfileSizeBytes\x12#\n" +
	"\rsegment_count\x18\x06 \x01(\x05R\fsegmentCount\x12#\n" +
	"\rplaylist_path\x18\a \x01(\tR\fplaylistPath\x12!\n" +
	"\fstorage_path\x18\b \x01(\tR\vstoragePath\"\xa8\x01\n" +
	"\x0fListJobsRequest\x12;\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x16.encoding.v1.JobStatusR\fstatusFilter\x12*\n" +
	"\x11content_id_filter\x18\x02 \x01(\tR\x0fcontentIdFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"g\n" +
	"\x10ListJobsResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.encoding.v1.JobStatusResponseR\x04jobs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount*\xa4\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x19\n" +
	"\x15JOB_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x052\xac\x01\n" +
	"\x0fEncodingService\x12P\n" +
	"\fGetJobStatus\x12 .encoding.v1.GetJobStatusRequest\x1a\x1e.encoding.v1.JobStatusResponse\x12G\n" +
	"\bListJobs\x12\x1c.encoding.v1.ListJobsRequest\x1a\x1d.encoding.v1.ListJobsResponseB]Z;github.com/streamvault/gateway/proto/encoding/v1;encodingv1\xaa\x02\x1dStreamVault.Proto.Encoding.V1b\x06proto3"

var (
	file_encoding_v1_encoding_proto_rawDescOnce sync.Once
	file_encoding_v1_encoding_proto_rawDescData []byte
)

func file_encoding_v1_encoding_proto_rawDescGZIP() []byte {
	file_encoding_v1_encoding_proto_rawDescOnce.Do(func() {
		file_encoding_v1_encoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encoding_v1_encoding_proto_rawDesc), len(file_encoding_v1_encoding_proto_rawDesc)))
	})
	return file_encoding_v1_encoding_proto_rawDescData
}

var file_encoding_v1_encoding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_encoding_v1_encoding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_encoding_v1_encoding_proto_goTypes = []any{
	(JobStatus)(0),                // 0: encoding.v1.JobStatus
	(*GetJobStatusRequest)(nil),   // 1: encoding.v1.GetJobStatusRequest
	(*JobStatusResponse)(nil),     // 2: encoding.v1.JobStatusResponse
	(*EncodingOutput)(nil),        // 3: encoding.v1.EncodingOutput
	(*ListJobsRequest)(nil),       // 4: encoding.v1.ListJobsRequest
	(*ListJobsResponse)(nil),      // 5: encoding.v1.ListJobsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_encoding_v1_encoding_proto_depIdxs = []int32{
	0, // 0: encoding.v1.JobStatusResponse.status:type_name -> encoding.v1.JobStatus
	3, // 1: encoding.v1.JobStatusResponse.outputs:type_name -> encoding.v1.EncodingOutput
	6, // 2: encoding.v1.JobStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: encoding.v1.JobStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	6, // 4: encoding.v1.JobStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	0, // 5: encoding.v1.ListJobsRequest.status_filter:type_name -> encoding.v1.JobStatus
	2, // 6: encoding.v1.ListJobsResponse.jobs:type_name -> encoding.v1.JobStatusResponse
	1, // 7: encoding.v1.EncodingService.GetJobStatus:input_type -> encoding.v1.GetJobStatusRequest
	4, // 8: encoding.v1.EncodingService.ListJobs:input_type -> encoding.v1.ListJobsRequest
	2, // 9: encoding.v1.EncodingService.GetJobStatus:output_type -> encoding.v1.JobStatusResponse
	5, // 10: encoding.v1.EncodingService.ListJobs:output_type -> encoding.v1.ListJobsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_encoding_v1_encoding_proto_init() }
func file_encoding_v1_encoding_proto_init() {
	if File_encoding_v1_encoding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encoding_v1_encoding_proto_rawDesc), len(file_encoding_v1_encoding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encoding_v1_encoding_proto_goTypes,
		DependencyIndexes: file_encoding_v1_encoding_proto_depIdxs,
		EnumInfos:         file_encoding_v1_encoding_proto_enumTypes,
		MessageInfos:      file_encoding_v1_encoding_proto_msgTypes,
	}.Build()
	File_encoding_v1_encoding_proto = out.File
	file_encoding_v1_encoding_proto_goTypes = nil
	file_encoding_v1_encoding_proto_depIdxs = nil
}
